version: '3.8'

services:
  freevoice-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: freevoice-website
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - freevoice-network

networks:
  freevoice-network:
    driver: bridge